apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "travelease.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "travelease.labels" . | nindent 4 }}
data:
  AWS_REGION:             {{ .Values.env.AWS_REGION | quote }}
  BEDROCK_REGION:         {{ .Values.env.BEDROCK_REGION | quote }}
  BEDROCK_MODEL_ID:       {{ .Values.env.BEDROCK_MODEL_ID | quote }}
  RECOMMENDATION_ENABLED: {{ .Values.env.RECOMMENDATION_ENABLED | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
