{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "travelease.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "travelease.labels" . | nindent 4 }}
    # Required for Prometheus Operator to discover this ServiceMonitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "travelease.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /actuator/prometheus
      port: http
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
