output "vpc_id" { value = module.vpc.vpc_id }
output "cluster_name" { value = module.eks.cluster_name }
output "cluster_endpoint" { value = module.eks.cluster_endpoint }
output "ecr_repository_url" { value = "See shared environment outputs" }
output "rds_endpoint" { value = module.rds.db_endpoint }
output "alb_controller_role_arn" { value = module.irsa_alb_controller.role_arn }
output "app_role_arn" { value = module.irsa_app.role_arn }
output "waf_acl_arn" { value = module.waf.web_acl_arn }
output "access_logs_bucket" { value = module.access_logging.logs_bucket_name }
output "secret_arn" { value = module.secrets_manager.secret_arn }
output "secret_name" { value = module.secrets_manager.secret_name }
